apiVersion: v1
kind: Service
metadata:
  name: jenkins-server
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
apiVersion: v1
kind: Service
metadata:
  name: jenkins-server
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
