apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-blueocean
        image: jenkins-blueocean:1.1
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
      nodeSelector:
        role: master
